"""added email to user table

Revision ID: 626023f68e7b
Revises: 69620c8e9e93
Create Date: 2020-04-05 21:00:25.821951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626023f68e7b'
down_revision = '69620c8e9e93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
